<a href="https://colab.research.google.com/github/ssjeson412/BDS-M1/blob/M1/recommender_systems/24th%20Sept%20M1_Recap_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
# Importing necessary libraries.
import pandas as pd
import scipy.sparse as ss
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_distances

In [85]:
df_trips = pd.read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')

In [86]:
df_trips.head()

,Unnamed: 0,username,country,country_code,country_slug,date_end,date_start,latitude,longitude,place,place_slug
0,0,@lewellenmichael,Mexico,MX,mexico,2018-06-15,2018-06-04,21,-101,Guanajuato,mexico
1,1,@lewellenmichael,Mexico,MX,mexico,2018-06-03,2018-05-31,19,-99,Mexico City,mexico-city-mexico
2,2,@lewellenmichael,Mexico,MX,mexico,2017-11-05,2017-11-01,21,-86,Cancun,cancun-mexico
3,3,@lewellenmichael,Jordan,JO,jordan,2017-08-07,2017-07-24,31,35,Amman,amman-jordan
4,4,@waylandchin,China,CN,china,2017-03-18,2017-02-17,40,122,Yingkou,china

In [87]:
# Creating user-place matrix using df_trips
trips_matrix = pd.crosstab(df_trips['username'], df_trips['place_slug'])
display(trips_matrix.head())

place_slug,11000,180-40,45230,630-72,671-03,847-00,a-coruna-spain,aachen-germany,aalborg-denmark,aalesund-norway,...,york-united-kingdom,zadar-croatia,zagreb-croatia,zambia,zhangjiakou-china,zhengzhou-china,zhuhai-china,zimbabwe,zurich-switzerland,zwolle-netherlands
username,,,,,,,,,,,,,,,,,,,,,
@01aniqe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@0chucha0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@10kjuan,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
@123456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@1ikigai,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [88]:
# Calculate the pairwise cosine distance matrix between users
user_distances = cosine_distances(matrix_user_place)

# Convert distances to similarity: similarity = 1 - distance
user_similarity = 1 - user_distances
print("User Similarity Matrix Shape:", user_similarity.shape)

# Display a slice of the similarity matrix
user_similarity

User Similarity Matrix Shape: (2871, 2871)

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.36335108,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.36335108, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [89]:
###################################################
#   Step 1: Label Encoding and Matrix Creation    #
###################################################
# Initialize label encoders
le_user = LabelEncoder()
le_place = LabelEncoder()
# Label encode usernames and place slugs
df_trips['username_id'] = le_user.fit_transform(df_trips['username'])
df_trips['place_slug_id'] = le_place.fit_transform(df_trips['place_slug'])

# Create a sparse matrix

# Create the sparse matrix using the 'username_id' and 'place_slug_id' columns as indices
matrix = pd.crosstab(df_trips['username_id'], df_trips['place_slug_id'])

###################################################
#    Step 2: Perform Dimensionality Reduction     #
###################################################
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
#These latent features could potentially capture characteristics like how popular a place is
matrix_places = svd.fit_transform(matrix.T)

###################################################
#    Step 3: Calculate The Similarity Matrix      #
###################################################
cosine_distance_matrix_places = cosine_distances(matrix_places)

In [90]:
cosine_distance_matrix_places.shape

(961, 961)

In [91]:
cosine_distance_matrix_places

array([[0.        , 0.93737257, 0.94042055, ..., 0.55101577, 0.94479183,
        0.66700793],
       [0.93737257, 0.        , 0.2219977 , ..., 0.55865144, 1.01683665,
        0.55894041],
       [0.94042055, 0.2219977 , 0.        , ..., 0.42547908, 0.90915149,
        0.12785817],
       ...,
       [0.55101577, 0.55865144, 0.42547908, ..., 0.        , 0.35913659,
        0.36126287],
       [0.94479183, 1.01683665, 0.90915149, ..., 0.35913659, 0.        ,
        0.89817704],
       [0.66700793, 0.55894041, 0.12785817, ..., 0.36126287, 0.89817704,
        0.        ]])

In [92]:
df_trips = pd.read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')
df_trips.shape # (46510, 14)

(46510, 11)

In [93]:
le_users, le_items = LabelEncoder(), LabelEncoder()
df_trips['username_id'] = le_users.fit_transform(df_trips['username'])
df_trips['place_slug_id'] = le_items.fit_transform(df_trips['place_slug'])
matrix_user_place = pd.crosstab(df_trips['username_id'], df_trips['place_slug_id'])
matrix_user_place.shape # (2871, 961)

(2871, 961)

In [94]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
matrix_user_place_dr = svd.fit_transform(matrix_user_place)
matrix_user_place_dr.shape # (2871, 5)

(2871, 5)

In [95]:
D = cosine_distances(matrix_user_place_dr) # (2871, 2871)
i = le_users.transform(['@cw'])[0] # 555
np.argsort(D[i, :])[:5] # [555, 2644, 153, 1371, 702]
le_users.inverse_transform(np.argsort(D[i, :])[:5])

array(['@cw', '@travpreneur', '@andrea', '@katehuentelman', '@dpashley'],
      dtype=object)

In [96]:
mine = df_trips[df_trips.username_id == 555]['place_slug_id'].unique()
theirs = df_trips[df_trips.username_id == 2644]['place_slug_id'].unique()
le_items.inverse_transform(theirs[~np.isin(theirs, mine)])[:10]

array(['pune-india', 'manchester-united-kingdom',
       'san-diego-ca-united-states', 'san-jose-ca-united-states',
       'amsterdam-netherlands', 'birmingham-united-kingdom',
       'mumbai-india', 'victoria-seychelles', 'johannesburg-south-africa',
       'delhi-india'], dtype=object)

In [97]:
matrix_place_user = matrix_user_place.T # (961, 2871)
matrix_place_user_dr = svd.fit_transform(matrix_place_user) # (961, 5)
Dp = cosine_distances(matrix_place_user_dr) # (961, 961)

In [98]:
j = le_items.transform(['paris-france'])[0] # 626
np.argsort(Dp[j, :])[:5] # [626, 735, 12, 172, 856]
le_items.inverse_transform(np.argsort(Dp[j, :])[:5])

array(['paris-france', 'france', 'grenoble-france', 'gothenburg-sweden',
       'malta'], dtype=object)

In [99]:
# Constructing the user-to-place matrix
user_place_matrix = pd.crosstab(df_trips['username'], df_trips['place_slug'])
print("Matrix Shape:", user_place_matrix.shape)
user_place_matrix.head()

Matrix Shape: (2869, 960)

place_slug,11000,180-40,45230,630-72,671-03,847-00,a-coruna-spain,aachen-germany,aalborg-denmark,aalesund-norway,...,york-united-kingdom,zadar-croatia,zagreb-croatia,zambia,zhangjiakou-china,zhengzhou-china,zhuhai-china,zimbabwe,zurich-switzerland,zwolle-netherlands
username,,,,,,,,,,,,,,,,,,,,,
@01aniqe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@0chucha0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@10kjuan,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
@123456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@1ikigai,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
# Importing necessary libraries.
import pandas as pd
import scipy.sparse as ss
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_distances

In [101]:
df_trips = pd.read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')

In [102]:
df_trips.shape

(46510, 11)

In [103]:
df_trips.username.value_counts()

username
@scottbrills        858
@adamnowek          678
@tkrunning          335
@replay             299
@photostraveller    255
                   ...
@kschroeder           1
@becky                1
@stollz               1
@arve                 1
@hannasoderq          1
Name: count, Length: 2871, dtype: int64

In [104]:
df_trips.country.value_counts()

country
United States     7573
Thailand          3372
United Kingdom    2230
Germany           2019
Spain             1975
                  ...
New Caledonia        1
Iguazu Falls         1
Åland Islands        1
Mayotte              1
Spania               1
Name: count, Length: 249, dtype: int64

In [105]:
df_trips.columns

Index(['Unnamed: 0', 'username', 'country', 'country_code', 'country_slug',
       'date_end', 'date_start', 'latitude', 'longitude', 'place',
       'place_slug'],
      dtype='object')

In [106]:
df_trips[['username', 'country']]

               username        country
0      @lewellenmichael         Mexico
1      @lewellenmichael         Mexico
2      @lewellenmichael         Mexico
3      @lewellenmichael         Jordan
4          @waylandchin          China
...                 ...            ...
46505         @antonioc           Cuba
46506         @antonioc     Costa Rica
46507         @antonioc  United States
46508         @jrearden  United States
46509       @kschroeder      Argentina

[46510 rows x 2 columns]

In [107]:
pd.crosstab(df_trips['username'], df_trips['country'])

country,11000,180 40,45230,630 72,671 03,847 00,AB30,AD100,Abkhazia,Afghanistan,...,Uruguay,Uzbekistan,Vatican City,Venezuela,Vietnam,Western Sahara,Yemen,Zambia,Zimbabwe,Åland Islands
username,,,,,,,,,,,,,,,,,,,,,
@01aniqe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@0chucha0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@10kjuan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@123456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@1ikigai,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
@zsoltee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@zuzapogopl,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@zwasham,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@zywy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@zzap,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [108]:
pd.crosstab(df_trips['username'], df_trips['country']).shape

(2869, 249)

In [109]:
matrix = pd.crosstab(df_trips['username'], df_trips['country'])

In [110]:
cosine_distances(matrix)

array([[0.       , 1.       , 1.       , ..., 1.       , 1.       ,
        1.       ],
       [1.       , 0.       , 1.       , ..., 1.       , 1.       ,
        1.       ],
       [1.       , 1.       , 0.       , ..., 1.       , 0.5150344,
        1.       ],
       ...,
       [1.       , 1.       , 1.       , ..., 0.       , 1.       ,
        1.       ],
       [1.       , 1.       , 0.5150344, ..., 1.       , 0.       ,
        1.       ],
       [1.       , 1.       , 1.       , ..., 1.       , 1.       ,
        0.       ]])

In [111]:
np.dot(matrix, matrix.T)

array([[  1,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0],
       [  0,   0, 861, ...,   0,  45,   0],
       ...,
       [  0,   0,   0, ...,   2,   0,   0],
       [  0,   0,  45, ...,   0,  10,   0],
       [  0,   0,   0, ...,   0,   0,   5]])

In [112]:
np.dot(matrix, matrix.T).shape

(2869, 2869)

In [113]:
pd.crosstab(df_trips['country'], df_trips['username'])

username,@01aniqe,@0chucha0,@10kjuan,@123456,@1ikigai,@5ee8688fa7e64c5,@7farah7,@9102180,@_yuks,@a,...,@zoxel,@zpeirce,@zrephel,@zrueda,@zsofiaszarka,@zsoltee,@zuzapogopl,@zwasham,@zywy,@zzap
country,,,,,,,,,,,,,,,,,,,,,
11000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180 40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45230,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
630 72,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
671 03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Yemen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zambia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Åland Islands,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [114]:
pd.crosstab(df_trips['country'], df_trips['username']).shape

(249, 2869)

In [115]:
matrix_user = pd.crosstab(df_trips['country'], df_trips['username'])

In [116]:
matrix_item = pd.crosstab(df_trips.country, df_trips.username)

In [117]:
np.dot(matrix, matrix.T)

array([[  1,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0],
       [  0,   0, 861, ...,   0,  45,   0],
       ...,
       [  0,   0,   0, ...,   2,   0,   0],
       [  0,   0,  45, ...,   0,  10,   0],
       [  0,   0,   0, ...,   0,   0,   5]])

In [118]:
np.dot(matrix, matrix.T).shape

(2869, 2869)

In [120]:
le_users.transform(['@scottbrills'])

array([2321])

In [122]:
le_country = LabelEncoder()
le_country.fit(df_trips['country'])
le_country.transform(['Denmark'])

array([70])

In [126]:
df_trips['username_id'] = le_users.fit_transform(df_trips['username'])
df_trips['country_id'] = le_country.fit_transform(df_trips['country'])

In [123]:
Matrix_item = pd.crosstab(df_trips.country, df_trips.username)

In [124]:
matrix_item_sin = cosine_distances(Matrix_item)

In [127]:
le_country.transform(['Denmark'])

array([70])

In [128]:
matrix_item_sin[70]

array([1.        , 0.97688749, 0.97688749, 0.97688749, 0.97688749,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.97301766, 1.        , 1.        , 0.95822663, 0.97724038,
       0.97688749, 0.94032376, 0.98966377, 0.95925547, 0.98665599,
       0.97226499, 0.98844375, 0.92579871, 0.88237889, 0.97212527,
       0.97688749, 0.99229583, 0.65331238, 0.98717949, 0.99314262,
       0.81629269, 0.99530387, 0.95377498, 0.97076473, 1.        ,
       0.95237879, 0.98980834, 1.        , 0.90611655, 0.83656989,
       0.98486931, 0.95838163, 1.        , 0.93462795, 0.91991089,
       1.        , 0.96721263, 1.        , 0.8549124 , 0.99570811,
       0.96899132, 1.        , 1.        , 1.        , 0.96524903,
       0.91290744, 0.97688749, 0.97932754, 0.9234831 , 1.        ,
       0.94249871, 1.        , 0.83659303, 0.78652044, 0.96419426,
       0.97351806, 0.97885225, 0.88077051, 1.        , 1.        ,
       0.        , 1.        , 0.9859015 , 1.        , 1.        ,
       0.63618674, 0.98486727, 0.99303132, 0.48012419, 0.93302625,
       1.        , 0.87990388, 0.87179487, 0.90473682, 0.97688749,
       0.93933453, 1.        , 0.98953483, 0.82746631, 1.        ,
       1.        , 0.8241423 , 0.91828494, 1.        , 0.97688749,
       0.99166406, 0.98365699, 1.        , 1.        , 0.97932754,
       1.        , 0.92666215, 1.        , 0.88788216, 1.        ,
       0.79609466, 0.85860349, 0.9457348 , 0.94418163, 0.77270921,
       0.90688339, 0.97331197, 0.84992781, 0.98441755, 0.96731398,
       0.94020571, 0.91085003, 1.        , 1.        , 1.        ,
       1.        , 0.96794872, 1.        , 1.        , 0.97667496,
       0.8626502 , 0.98224448, 1.        , 1.        , 0.93066248,
       0.93066248, 0.84053308, 1.        , 0.94972666, 0.99614792,
       0.74201575, 0.93309613, 0.95839749, 0.91712889, 0.79487649,
       0.92087488, 1.        , 1.        , 0.94086876, 0.97688749,
       0.88443746, 0.9297604 , 0.99741594, 0.95107195, 0.93251181,
       0.73175719, 0.9495834 , 1.        , 0.81535409, 0.99338893,
       0.97743787, 0.96356356, 0.84270584, 1.        , 0.7502236 ,
       0.91718245, 1.        , 0.97076473, 0.9953775 , 0.35239348,
       0.93061113, 1.        , 1.        , 1.        , 1.        ,
       0.89002785, 1.        , 0.99699101, 1.        , 0.95666805,
       1.        , 0.98059213, 0.8730295 , 0.86379921, 0.97688749,
       1.        , 1.        , 0.95865509, 0.63772992, 0.97688749,
       1.        , 0.94662395, 0.96669438, 0.97204979, 0.98150999,
       1.        , 0.94831886, 1.        , 0.98365699, 1.        ,
       0.98112872, 1.        , 0.98112872, 1.        , 0.99627643,
       1.        , 0.97367984, 0.98365699, 1.        , 0.92068346,
       0.98665599, 0.91114929, 0.96969441, 1.        , 1.        ,
       0.93066248, 0.96838379, 0.96086739, 1.        , 0.90693536,
       1.        , 0.84015785, 0.93066248, 1.        , 1.        ,
       0.84103504, 0.90268698, 0.97006384, 0.93119791, 0.93335676,
       0.86631966, 0.89017178, 0.61302363, 0.95097097, 0.98966377,
       0.94769617, 0.89291013, 1.        , 0.99182849, 0.97733632,
       0.97569721, 0.90765401, 0.91190421, 0.81680553, 0.97862837,
       0.95440392, 0.97529169, 0.96153846, 0.94320512, 0.97688749,
       1.        , 0.96153846, 0.96419426, 1.        ])

In [130]:
matrix_item_sin[70].size

249

In [131]:
matrix_item_sin[70].argsort()

array([ 70, 164,  78, 227,  75, 183,  27, 150, 135, 159, 109,  63, 139,
       105, 153,  30, 238,  91,  88,  39,  62, 216, 131, 220, 157, 112,
        48, 106, 125, 178, 225,  82, 177,  81,  67,  23, 145, 103, 170,
       226, 231, 221,  83,  38, 110, 214, 236, 116, 206, 237,  55, 138,
       160,  92,  44, 204, 140,  58,  22, 101, 146, 165, 129, 210, 217,
       130, 223, 149,  79, 136, 224,  43,  85, 115,  16, 143,  60, 243,
       108, 107, 186, 230, 191, 151, 133, 228, 148,  35,  32, 240, 174,
        13,  41, 137, 182,  18, 212, 242, 246, 156,  64, 247,  54, 187,
        46, 114, 121, 211,  50, 207, 222, 162,  33, 188,  24,  20,  10,
       111,  65, 201, 241, 235, 124,  56,   3,  15,  25,   1,   2,   4,
       144, 179, 184, 244,  94,  84,  14, 234, 155, 239,  66,  57,  99,
       176, 197, 195, 189, 126,  96, 193, 202, 113,  76,  40,  72,  19,
       205,  28,  21,  87, 229,  17,  36,  95, 233,  26,  77,  29, 154,
        31, 163,  49, 134, 199, 172, 147,   7,   6,   5,   0,  11,   9,
         8,  12,  47,  45,  42,  51,  52,  53,  59,  61, 127, 120, 122,
       123, 118, 117, 119, 104, 102, 100,  97,  98,  86,  89,  90,  93,
        73,  74,  69,  80,  68,  71,  34,  37, 128, 132, 161, 168, 142,
       141, 152, 158, 190, 185, 181, 180, 171, 169, 173, 175, 167, 166,
       192, 194, 198, 196, 203, 200, 218, 219, 213, 215, 208, 209, 232,
       245, 248])

In [132]:
le_country.inverse_transform(matrix_item_sin[70].argsort())

array(['Denmark', 'Norway', 'Estonia', 'Timor-Leste', 'Ecuador', 'Qatar',
       'Bangladesh', 'Montenegro', 'Macedonia (FYROM)', 'New Zealand',
       'Israel', 'Cuba', 'Maldives', 'India', 'Myanmar', 'Belgium',
       'United States', 'Greece', 'Germany', 'Bosnia-Herzegovina',
       'Croatia', 'Sri Lanka', 'Lithuania', 'Sweden', 'Netherlands',
       'Japan', 'Canada', 'Indonesia', 'Latvia', 'Portugal', 'Thailand',
       'Fiji', 'Poland', 'Faroe Islands', 'Czechia', 'Austria',
       'Mediterranean Sea', 'Iceland', 'Panama', 'The Bahamas', 'Turkey',
       'Switzerland', 'Finland', 'Bosnia and Herzegovina', 'Italy',
       'Spain', 'United Arab Emirates', 'Kenya', 'Slovakia',
       'United Kingdom', 'China', 'Malaysia', 'Nicaragua', 'Greenland',
       'Bulgaria', 'Singapore', 'Malta', 'Colombia', 'Australia',
       'Hungary', 'Mexico', 'Oman', 'Libya', 'Somalia', 'Sudan',
       'Liechtenstein', 'Tajikistan', 'Mongolia', 'Ethiopia',
       'Madagascar', 'Tanzania', 'Brunei', 'France', 'Kazakhstan',
       'Antarctica', 'Mauritius', 'Costa Rica', 'Vietnam', 'Ireland',
       'Iran', 'Reunion', 'Tunisia', 'Saint Kitts and Nevis', 'Morocco',
       'Luxembourg', 'Tonga', 'Monaco', 'Bhutan', 'Benin', 'Uzbekistan',
       'Peru', 'Andorra', 'Brazil', 'Malawi', 'Puerto Rico', 'Argentina',
       'South Korea', 'Venezuela', 'Zambia', 'Nepal', 'Curaçao',
       'Zimbabwe', 'Chile', 'Romania', 'Cambodia', 'KY16', 'Kyrgyzstan',
       'South Africa', 'Caribbean Netherlands', 'Slovenia', 'Taiwan',
       'Nigeria', 'Bermuda', 'Russia', 'Azerbaijan', 'Aruba', 'Albania',
       'Jamaica', 'Cyprus', 'Serbia', 'Vatican City', 'Ukraine', 'Laos',
       'Cocos (Keeling) Islands', '630 72', 'Anguilla',
       'Bab al-Mandab Strait', '180 40', '45230', '671 03', 'Mayotte',
       'Prishtina', 'Red Sea', 'Western Sahara', 'Guadeloupe', 'Finnland',
       'Angola', 'Uganda', 'Namibia', 'Uruguay', 'Czech Republic',
       'Collectivity of Saint Martin', 'Honduras', 'Philippines',
       'San Marino', 'Saint-Barthélemy', 'Rwanda', 'Lebanon', 'Guernsey',
       'Saint Martin', 'Seychelles', 'Jordan', 'Egypt', 'Botswana',
       'Dominican Republic', 'Armenia', 'Sint Maarten', 'Barbados',
       'Atlantic Ocean', 'Georgia', 'Trinidad and Tobago',
       'Antigua and Barbuda', 'Bolivia', 'Guatemala',
       'U.S. Virgin Islands', 'Bahrain', 'El Salvador', 'Belarus',
       'Myanmar (Burma)', 'Belize', 'North Korea', 'Cape Verde',
       'Macedonia', 'Saudi Arabia', 'Paraguay', 'Moldova', 'AD100',
       'AB30', '847 00', '11000', 'Algeria', 'Afghanistan', 'Abkhazia',
       'Andaman Sea', 'Cameroon', 'Burundi', 'British Virgin Islands',
       'Caribbean Sea', 'Cayman Islands', 'Chad', 'Cook Islands',
       'Crimea', 'Leh', 'Kuwait', 'LL48', 'Lake Titicaca', 'Kosovo',
       'Khammouane Province', 'Kurdistan', 'Iguazu Falls', 'IV51',
       'Hong Kong', 'Guinea', 'Haiti', 'French Polynesia', 'Ghana',
       'Gibraltar', 'Grenada', 'EX17', 'East Timor', 'DG6', 'Europe',
       "Côte d'Ivoire", 'Djibouti', 'Bethlehem', 'Bosnia', 'Lesotho',
       'Lower Subansiri', 'Nicosia', 'Palau', 'Martinique', 'Mars',
       'Mozambique', 'New Caledonia', 'Saint Barthélemy',
       'Republic of Macedonia', 'Prizren District', 'Pristina District',
       'Papua New Guinea', 'Palestine', 'Patagonia', 'Perú', 'Pakistan',
       'Pai', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Sanur',
       'Samoa', 'Sierra Leone', 'Senegal', 'Svalbard and Jan Mayen',
       'Swaziland', 'South Sudan', 'Spania', 'Slovensko',
       'Solomon Islands', 'Turks and Caicos Islands', 'Yemen',
       'Åland Islands'], dtype=object)

In [133]:
le_country.inverse_transform(matrix_item_sin[70].argsort()).size

249